name: Deploy

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: npm install

    - name: Build and deploy APIs
      run: npm start
        
